# GoReleaser configuration for stegodon
version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Update go mod
    - go mod tidy

builds:
  - id: stegodon
    binary: stegodon
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: stegodon-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CLAUDE.md
      - DOCKER.md
      - config.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Documentation Updates"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: deemkeen
    name: stegodon
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## stegodon v{{ .Version }}

    SSH-first federated blogging platform with ActivityPub support.

    ### Installation

    Download the appropriate binary for your system:
    - **Linux AMD64**: `stegodon_{{ .Version }}_Linux_x86_64.tar.gz`
    - **Linux ARM64**: `stegodon_{{ .Version }}_Linux_arm64.tar.gz`
    - **macOS AMD64 (Intel)**: `stegodon_{{ .Version }}_Darwin_x86_64.tar.gz`
    - **macOS ARM64 (Apple Silicon)**: `stegodon_{{ .Version }}_Darwin_arm64.tar.gz`

    Extract and run:
    ```bash
    tar xzf stegodon_{{ .Version }}_*.tar.gz
    chmod +x stegodon
    ./stegodon
    ```

    Or use Docker:
    ```bash
    docker pull ghcr.io/deemkeen/stegodon:{{ .Version }}
    docker-compose up -d
    ```

    ### Quick Start

    ```bash
    # Run stegodon
    ./stegodon

    # Connect via SSH
    ssh localhost -p 23232
    ```

    See README.md for full documentation.
  footer: |
    ---
    **Full Changelog**: https://github.com/deemkeen/stegodon/compare/{{ .PreviousTag }}...{{ .Tag }}

announce:
  skip: true
